version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-patch
  # Maintain dependencies for Cargo
  - # ignore patch updates
    package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-patch
