name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      #- name: Cargo check
      #  run: cargo check --target aarch64-apple-ios-sim

      #- name: Cargo check
      #  run: cargo build --target aarch64-apple-ios-sim

      - name: start simulator
        run: xcrun simctl boot 'iPhone 16'

        #- name: Run example and take screenshot
        #  run: |
        #    make install
        #    make run &
        #    sleep 10
        #    xcrun simctl io booted screenshot screenshot.png

      - name: Run example and take screenshot
        run: |
          sleep 10
          xcrun simctl io booted screenshot screenshot.png

      - uses: actions/upload-artifact@v4
        id: screenshot-upload-step
        with:
          name: screenshot
          path: screenshot.png
          compression-level: 0 # no compression

          #- name: Put screenshot in github summary
          #  run: |
          #    echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
          #    echo "## Heading" >> "$GITHUB_STEP_SUMMARY"
          #    echo "Uploading image..."
          #    mkdir -p "$GITHUB_WORKSPACE/artifacts"
          #    cp ./image.png "$GITHUB_WORKSPACE/artifacts/"
          #    echo "image_path=$GITHUB_WORKSPACE/artifacts/image.png" >> $GITHUB_OUTPUT
          #    echo "image" >> "$GITHUB_STEP_SUMMARY"

      - name: Put screenshot in github summary
        run: |
          echo 'Artifact ID is ${{ steps.screenshot-upload-step.outputs.artifact-id }}'
          echo 'Artifact URL is ${{ steps.screenshot-upload-step.outputs.artifact-url }}'
          echo "## SCREENSHOT" >> "$GITHUB_STEP_SUMMARY"

          echo "![Screenshot](data:image/png;base64,$(base64 -i screenshot.png))"
          echo "![Screenshot](data:image/png;base64,$(base64 -i screenshot.png))" >> "$GITHUB_STEP_SUMMARY"
